name = "smxitalia-littlelink"
compatibility_date = "2025-01-27"
workers_dev = true
pattern = "join.smxitalia.com"
custom_domain = true

[assets]
directory = "./"
html_handling = "auto-trailing-slash"

[[routes]]
pattern = "join.smxitalia.com"
custom_domain = true
